name: CI - Airflow, Python, dbt Validation

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  BQ_DATASET: ${{ secrets.BQ_DATASET }}
  BQ_TABLE_ECOM_PRODUCTS: ${{ secrets.BQ_TABLE_ECOM_PRODUCTS }}
  BQ_TABLE_ECOM_CUSTOMERS_ECOM: ${{ secrets.BQ_TABLE_ECOM_CUSTOMERS_ECOM }}
  BQ_TABLE_ECOM_ORDERS: ${{ secrets.BQ_TABLE_ECOM_ORDERS }}
  DBT_PROJECT_DIR: ./include/dbt_project
  DBT_PROFILES_DIR: ./include/dbt_project
  POSTGRES_CONN: ${{ secrets.POSTGRES_CONN }}

jobs:
  validate:
    name: Validate Airflow DAGs, Python Lint, and dbt
    runs-on: ubuntu-latest

    steps:
      # --------------------------
      # 1️⃣ Checkout repo
      # --------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------
      # 2️⃣ Set up Python
      # --------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # --------------------------
      # 3️⃣ Install dependencies
      # --------------------------
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow dbt-bigquery flake8

      # --------------------------
      # 4️⃣ Lint all Python code
      # --------------------------
      - name: Run flake8 (Python lint)
        run: |
          echo "Running Python lint check..."
          flake8 . --max-line-length=100 --ignore=E203,E266,E501,W503,F403,F401

      # --------------------------
      # 5️⃣ Validate Airflow DAGs
      # --------------------------
      - name: Validate Airflow DAGs
        run: |
          echo "Validating Airflow DAGs..."
          airflow version
          airflow db migrate || airflow db init || true
          airflow dags list

      # --------------------------
      # 6️⃣ Debug Repo Structure
      # --------------------------
      - name: Debug repository structure
        run: |
          echo "Listing repository contents..."
          ls -R

      # --------------------------
      # 7️⃣ Validate dbt (syntax only)
      # --------------------------
      - name: Validate dbt project syntax
        run: |
          echo "Validating dbt project syntax..."

          DBT_PROJECT_DIR="$(pwd)/include/dbt_project"
          DBT_PROFILES_DIR="$(pwd)/include/dbt_project"
          echo "Project dir: $DBT_PROJECT_DIR"
          echo "Profiles dir: $DBT_PROFILES_DIR"
          
          dbt deps --project-dir "$DBT_PROJECT_DIR" --profiles-dir "$DBT_PROFILES_DIR"
          dbt parse --project-dir "$DBT_PROJECT_DIR" --profiles-dir "$DBT_PROFILES_DIR"


      # --------------------------
      # ✅ Success message
      # --------------------------
      - name: Done
        run: echo "✅ All checks passed — ready to merge or deploy!"
